project_id = "ldvhmnimeozveydriwbl"

[functions.treatment-navigator]
verify_jwt = true

[functions.trial-finder]
verify_jwt = true

[functions.tts-generate]
verify_jwt = true

[functions.scan-reader]
verify_jwt = false
